blank_issues_enabled: false
contact_links:
  - name: Suporte & Atendimento Oficial Telegram
    url: https://t.me/xprotorkzdev
    about: Tire dúvidas e fale com a engenharia do Antigravity Turbinado
